Updated
scratchdesignstudio/info pull request #24
Opened 2016-10-27 12:55 UTC by coke11

Hey there! I updated the info site, but along with that came the following bugs

- [Menu isn't working] 
- [br's weren't working right for unique description] 

I cleared all current translations and made one with google translate just to show it is possible. I will work on fixing these bugs really soon... Maybe one of you could help me?

ALSO - I am working on updating the formatter. I have some good ideas :D

2016-10-27 13:27 UTC, TheGrits requested changes
Thanks for wanting to help out, but at this point this will do more damage than help. The HTML looks pretty good, just a few minor changes need to be made. The l10n.json file, however, is on the wrong track. We shouldn't be getting rid of translations just because the unique part of it is outdated, the standard part is still very useful! We should just be replacing the outdated uniques with "translation needed".

Thanks again for wanting to help!

2016-10-27 13:27 UTC, TheGrits commented on index.html
> +Create a project that contains 10 squares on the screen at a time, and 10 squares only. It could be a train driving on a track, with the train made out of 7 squares, and the tracks made out of 3. It
Please indent this line so that it is even with the other lines, just easier for editing in the future

2016-10-27 13:27 UTC, TheGrits commented on index.html
> -              <img src="//cdn.scratch.mit.edu/get_image/user/713038_170x170.png" alt="joletole Avatar" />
joletole is still a curator iirc (Thus please don't remove them)

2016-10-27 13:27 UTC, TheGrits commented on index.html
> +          <li>
The list of curators should be alphabetical.

2016-10-27 13:27 UTC, TheGrits commented on l10n.js
> -    "language":"English",
Uhh, why remove the perfectly fine English? You just need to change the 'unique' part of the description, not the whole thing.

2016-10-27 13:27 UTC, TheGrits commented on l10n.js
> -  "es": {
Whoa now! The 'standard' part of the translated descriptions are still very useful, we shouldn't be removing them! What we do is just change the 'unique' part to `Translation Needed!`

2016-10-27 13:27 UTC, TheGrits commented on l10n.js
>    "fr": {
We'd prefer to keep hand translated translations over Google translated translations.

2016-10-27 20:50 UTC, coke11 commented
Ok. So once I make the needed changes, this should be good to go?

2016-10-27 20:50 UTC, coke11 commented on l10n.js
>    "fr": {
I know. This was just temporary.

2016-10-27 20:51 UTC, coke11 commented on l10n.js
> -    "language":"English",
I fixed this later (in a nother commit)

2016-10-27 20:51 UTC, coke11 commented on l10n.js
> -  "es": {
Ok. Then we would alert the translators on their profile?

2016-10-27 20:51 UTC, coke11 commented on index.html
> -              <img src="//cdn.scratch.mit.edu/get_image/user/713038_170x170.png" alt="joletole Avatar" />
Oh, sorry about that. but doesn't it say for this studio?

2016-10-27 20:51 UTC, coke11 commented on index.html
> +          <li>
Oops. I will fix that asap

2016-10-27 20:52 UTC, coke11 commented on index.html
> +Create a project that contains 10 squares on the screen at a time, and 10 squares only. It could be a train driving on a track, with the train made out of 7 squares, and the tracks made out of 3. It
Sorry about that

2016-10-31 18:42 UTC, TheGrits commented on l10n.js
> -  "es": {
@coke11 Yep, I'll contact some of the translators right now.

2016-11-01 11:45 UTC, TheGrits commented
@coke11 I think so. Do you have any idea as to when you will be done?

2016-11-03 23:56 UTC, coke11 commented
@TheGrits Sorry - I have been really busy lately. I should have them done by Saturday :)

2016-11-04 01:35 UTC, TheGrits commented
@coke11 No worries, I'm busy these days too!

2016-12-01 22:57 UTC, coke11 commented
@TheGrits Well, I am so busy these day XD! Why don't we just delete this and start fresh for the next one ?

2016-12-01 22:57 UTC, closed without merging